version: '2'

services:
  http-server:
    image: 'httpd:2.4.38'
    ports:
      - '8000:80'
    volumes:
      - "$PWD/netboot:/usr/local/apache2/htdocs"

  nfs-server:
    image: "erichough/nfs-server"
    container_name: "nfs-server"
    cap_add:
      - SYS_ADMIN
    ports:
    - "2049:2049"
    - "2049:2049/udp"
    - "111:111"
    - "111:111/udp"
    - "32765:32765"
    - "32765:32765/udp"
    - "32767:32767"
    - "32767:32767/udp"
    volumes:
      - "$PWD/exports.txt:/etc/exports:ro"
      - "$PWD/nfs-export:/srv/nfs"
    environment:
      NFS_VERSION: 4.2
